language: node_js
node_js:
 - "node"
sudo: required
services:
  - docker
script:
 - npm install -g ionic cordova
 - cd client
 - npm install
 - ionic build
 - cd ../server
 - docker build . -t rgse/brew-logs