language: node_js
node_js:
- node
sudo: required
services:
- docker
script:
- npm install -g ionic cordova
- cd client
- npm install
- ionic cordova build browser
- docker build . -t rgse/brew-logs-client
- cd ../server-java
- mvn clean package
- docker build . -t rgse/brew-logs-server
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin http://5.45.97.155:5000
- docker push http://5.45.97.155:5000/rgse/brew-logs-client
- docker push http://5.45.97.155:5000/rgse/brew-logs-server