camunda.bpm:
  admin-user:
    id: kermit
    password: superSecret
    firstName: Kermit
  filter:
    create: All tasks

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:~/h2/brew
    userName: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update