dataSourceConfig:
  driverName: h2
  jndiName: java:jboss/datasources/ExampleDS
  jta: true
  spy: true
  connectionUrl: jdbc:h2:~/h2/brew;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  userName: sa
  password: sa